name: shopsphere
description: "A new Flutter project."


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

#---------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  #Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  lottie: ^3.1.2
  shimmer: ^3.0.0
  url_launcher: ^6.3.0
  connectivity_plus: ^6.0.4
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0

  #Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  #State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  #Product Specific
  readmore: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

  #Firebase
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.2.0
  google_sign_in: ^6.2.1

#---------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  #---------------- LOCAL ASSETS ------------------#
  assets:
    - assets/icons/brands/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/logos/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/content/
    - assets/images/reviews/
    - assets/icons/payment_methods/

  #---------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800